Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -36,17 +36,15 @@ jobs:
 
     - name: Configure CMake
       run: >
-        cmake -B ${{ github.workspace }}/build
+        cmake -S . -B build
         -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
         -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
         -DCMAKE_BUILD_TYPE=Release
-        -S ${{ github.workspace }}
-
 
     - name: Build
-      run: cmake --build ${{ steps.vars.outputs.build_dir }} --config Release
+      run: cmake --build build --config Release
 
     - name: Run tests (if any)
-      working-directory: ${{ steps.vars.outputs.build_dir }}
-      run: |
-        ctest --build-config Release || echo "No tests found or some failed"
+      working-directory: build
+      run: ctest --build-config Release || echo "No tests found or some failed"
+
